#!/usr/bin/env python3
"""Build the bilingual Fact Atlas demo-video script as a polished Word document."""

from __future__ import annotations

import argparse
from pathlib import Path

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_ALIGN_VERTICAL, WD_ROW_HEIGHT_RULE, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


INK = "11120F"
MUTED = "5F645E"
VIOLET = "7865FF"
VIOLET_SOFT = "EDE9FF"
LIME = "B8FF5C"
CYAN = "BCECF2"
PINK = "FFBED8"
YELLOW = "FFE38A"
PAPER = "F8F7F2"
WHITE = "FFFFFF"
BLUE = "3C49DA"

SCENES = [
    {
        "number": "01",
        "time": "00:00–00:14",
        "title": "Frame the problem and product / 问题与产品开场",
        "screen": "Open on the centered mobile Fact Atlas shell, then show a desktop/mobile comparison. Make the responsive adaptation and the Relay, Atlas, and Signals tabs unmistakable.",
        "narration": "个人知识库最危险的，不是缺少信息，而是把未经验证的说法当成事实。Fact Atlas 同时适配网页端和手机端，用三个标签连接主动探索与每日发现。",
        "subtitles": [
            ("00:00.000 → 00:06.500", "A personal knowledge base fails when unverified claims quietly become facts."),
            ("00:06.500 → 00:14.000", "Fact Atlas adapts to desktop and mobile, connecting active exploration and daily discovery in three tabs."),
        ],
        "color": VIOLET,
    },
    {
        "number": "02",
        "time": "00:14–00:30.5",
        "title": "Show both knowledge paths / 展示两条知识路径",
        "screen": "Show Relay text/link/image inputs, then switch to Signals. Select a topic and date, and swipe one news card at a time.",
        "narration": "在 Relay，你可以提交文本、公开链接或截图，发起一次深度核验。Signals 按主题和日期抓取全球新闻，一次只呈现一张可滑动卡片。",
        "subtitles": [
            ("00:14.000 → 00:22.000", "Relay accepts text, a public link, or a screenshot for deep verification."),
            ("00:22.000 → 00:30.500", "Signals routes global news by topic and date, one swipeable card at a time."),
        ],
        "color": LIME,
    },
    {
        "number": "03",
        "time": "00:30.5–00:46.5",
        "title": "Rank, then verify / 先筛选，再核验",
        "screen": "Hold on the live Gonka Signals receipt and importance label. Select one signal with Deep verify and show it arriving in Relay.",
        "narration": "第一道 Gonka 筛选只判断重要性，并保留请求回执；它不冒充真实度。你选中一条候选后，它才进入 FactRelay 的证据检索与交叉验证。",
        "subtitles": [
            ("00:30.500 → 00:38.500", "Gonka ranks importance and keeps a receipt; importance is never presented as truth."),
            ("00:38.500 → 00:46.500", "A selected signal then enters FactRelay evidence retrieval and cross-checking."),
        ],
        "color": CYAN,
    },
    {
        "number": "04",
        "time": "00:46.5–01:03",
        "title": "Inspect evidence and deterministic score / 证据与确定性评分",
        "screen": "Show the numbered source ledger, then the Truth Score and its model-consensus/source-evidence breakdown.",
        "narration": "每条公开来源都保留发布者、日期、链接、立场和可信度。Truth Score 由确定性代码计算，不由任何模型随口给分。",
        "subtitles": [
            ("00:46.500 → 00:55.000", "Every source keeps its publisher, date, URL, stance, and reliability."),
            ("00:55.000 → 01:03.000", "Truth Score is calculated by deterministic code, not generated by a model."),
        ],
        "color": PINK,
    },
    {
        "number": "05",
        "time": "01:03–01:19.5",
        "title": "Preserve disagreement and bounded agents / 保留分歧与边界",
        "screen": "Show the source-index validation note, then reveal the FactRelay supervisor coordinating its six bounded subagents and reusable Skills.",
        "narration": "无效来源编号会被拒绝，模型分歧也会原样保留。FactRelay 主 Agent 编排六个子 Agent：受理、证据、调查、质疑、裁决和回执。",
        "subtitles": [
            ("01:03.000 → 01:11.500", "Invalid source indexes are rejected, and model disagreement stays visible."),
            ("01:11.500 → 01:19.500", "The FactRelay supervisor coordinates six bounded subagents and reusable Skills."),
        ],
        "color": YELLOW,
    },
    {
        "number": "06",
        "time": "01:19.5–01:36.5",
        "title": "Compare adversarial models / 比较双模型",
        "screen": "Pause on the lime Kimi investigator card and violet MiniMax skeptic card, including their bilingual reasoning bullets.",
        "narration": "Kimi-K2.6 担任调查方，先形成基于证据的判断。MiniMax-M2.7 担任质疑方，专查循环引用、时间错位和遗漏背景。",
        "subtitles": [
            ("01:19.500 → 01:28.000", "Kimi-K2.6 forms the first evidence-based investigation."),
            ("01:28.000 → 01:36.500", "MiniMax-M2.7 challenges circular reporting, chronology, and missing context."),
        ],
        "color": VIOLET,
    },
    {
        "number": "07",
        "time": "01:36.5–01:53",
        "title": "Keep the real receipts / 保留真实回执",
        "screen": "Show the Proof block with non-null request IDs, then cut to the Gonka-only architecture boundary.",
        "narration": "每次推理都保留 Gonka 上游 Request ID 和执行顺序。所有语义推理只通过 GonkaRouter；回执证明调用来源，不等于证明事实。",
        "subtitles": [
            ("01:36.500 → 01:45.000", "Every inference preserves its upstream Gonka Request ID and order."),
            ("01:45.000 → 01:53.000", "All inference uses GonkaRouter; a receipt proves provenance, not truth."),
        ],
        "color": CYAN,
    },
    {
        "number": "08",
        "time": "01:53–02:11",
        "title": "Human gate to the Mapbox Atlas / 人工门与知识地球",
        "screen": "Confirm a Nominatim place candidate, switch to Atlas, and reveal the bright score marker on the dark Mapbox globe.",
        "narration": "最终由用户决定什么进入知识星球，并亲自确认地点候选。Atlas 使用深色 Mapbox 地球，让亮色事实节点和可解释关联一眼可见。",
        "subtitles": [
            ("01:53.000 → 02:01.000", "The user decides what enters the Atlas and confirms the place candidate."),
            ("02:01.000 → 02:11.000", "A dark Mapbox globe makes bright fact nodes and explainable links visible."),
        ],
        "color": LIME,
    },
    {
        "number": "09",
        "time": "02:11–02:25",
        "title": "Keep uncertainty honest / 诚实保留不确定性",
        "screen": "Show the unplaced-orbit state and browser-local privacy copy, then return to the complete Atlas node detail.",
        "narration": "没有可靠地点的知识会留在未落位轨道；系统绝不伪造坐标。完整证据快照只保存在当前浏览器，形成可回看的私人知识谱系。",
        "subtitles": [
            ("02:11.000 → 02:19.000", "Knowledge without a reliable place remains unplaced; coordinates are never invented."),
            ("02:19.000 → 02:25.000", "The evidence snapshot stays browser-local as a private knowledge lineage."),
        ],
        "color": YELLOW,
    },
    {
        "number": "10",
        "time": "02:25–02:30",
        "title": "Close / 收尾",
        "screen": "Hold on the Fact Atlas name, tagline, public demo URL, and GitHub URL.",
        "narration": "Fact Atlas：构建你的知识世界，让每条事实都保留回执。",
        "subtitles": [("02:25.000 → 02:30.000", "Fact Atlas. Build a knowledge world. Every fact keeps receipts.")],
        "color": PINK,
    },
]


def shade(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = tc_pr.find(qn("w:shd"))
    if shd is None:
        shd = OxmlElement("w:shd")
        tc_pr.append(shd)
    shd.set(qn("w:fill"), fill)


def set_cell_margins(cell, top=90, start=130, bottom=90, end=130) -> None:
    tc = cell._tc
    tc_pr = tc.get_or_add_tcPr()
    tc_mar = tc_pr.first_child_found_in("w:tcMar")
    if tc_mar is None:
        tc_mar = OxmlElement("w:tcMar")
        tc_pr.append(tc_mar)
    for margin, value in (("top", top), ("start", start), ("bottom", bottom), ("end", end)):
        node = tc_mar.find(qn(f"w:{margin}"))
        if node is None:
            node = OxmlElement(f"w:{margin}")
            tc_mar.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def set_cell_width(cell, width: int) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_w = tc_pr.find(qn("w:tcW"))
    if tc_w is None:
        tc_w = OxmlElement("w:tcW")
        tc_pr.append(tc_w)
    tc_w.set(qn("w:w"), str(width))
    tc_w.set(qn("w:type"), "dxa")


def set_table_geometry(table, widths: list[int], indent: int = 120) -> None:
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    tbl_pr = table._tbl.tblPr
    tbl_w = tbl_pr.find(qn("w:tblW"))
    if tbl_w is None:
        tbl_w = OxmlElement("w:tblW")
        tbl_pr.append(tbl_w)
    tbl_w.set(qn("w:w"), str(sum(widths)))
    tbl_w.set(qn("w:type"), "dxa")
    tbl_ind = tbl_pr.find(qn("w:tblInd"))
    if tbl_ind is None:
        tbl_ind = OxmlElement("w:tblInd")
        tbl_pr.append(tbl_ind)
    tbl_ind.set(qn("w:w"), str(indent))
    tbl_ind.set(qn("w:type"), "dxa")
    grid = table._tbl.tblGrid
    for child in list(grid):
        grid.remove(child)
    for width in widths:
        col = OxmlElement("w:gridCol")
        col.set(qn("w:w"), str(width))
        grid.append(col)
    for row in table.rows:
        row.height_rule = WD_ROW_HEIGHT_RULE.AT_LEAST
        cant_split = OxmlElement("w:cantSplit")
        row._tr.get_or_add_trPr().append(cant_split)
        for index, cell in enumerate(row.cells):
            set_cell_width(cell, widths[min(index, len(widths) - 1)])
            set_cell_margins(cell)
            cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER


def set_font(run, size: float | None = None, bold: bool | None = None, color: str | None = None, name: str = "STSong") -> None:
    run.font.name = name
    r_fonts = run._element.get_or_add_rPr().rFonts
    for key in ("w:ascii", "w:hAnsi", "w:eastAsia", "w:cs"):
        r_fonts.set(qn(key), name)
    if size is not None:
        run.font.size = Pt(size)
    if bold is not None:
        run.bold = bold
    if color is not None:
        run.font.color.rgb = RGBColor.from_string(color)


def set_paragraph_border(paragraph, color=INK, size=10, space=1, side="bottom") -> None:
    p_pr = paragraph._p.get_or_add_pPr()
    p_bdr = p_pr.find(qn("w:pBdr"))
    if p_bdr is None:
        p_bdr = OxmlElement("w:pBdr")
        p_pr.append(p_bdr)
    border = OxmlElement(f"w:{side}")
    border.set(qn("w:val"), "single")
    border.set(qn("w:sz"), str(size))
    border.set(qn("w:space"), str(space))
    border.set(qn("w:color"), color)
    p_bdr.append(border)


def add_field(paragraph, instruction: str) -> None:
    run = paragraph.add_run()
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = instruction
    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")
    text = OxmlElement("w:t")
    text.text = "1"
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    for node in (begin, instr, separate, text, end):
        run._r.append(node)


def add_label_paragraph(doc: Document, label: str, text: str, fill: str = PAPER) -> None:
    table = doc.add_table(rows=1, cols=1)
    table.style = "Table Grid"
    set_table_geometry(table, [9360])
    cell = table.cell(0, 0)
    shade(cell, fill)
    p = cell.paragraphs[0]
    p.paragraph_format.space_after = Pt(0)
    r = p.add_run(label.upper() + "\n")
    set_font(r, 7.5, True, VIOLET)
    r2 = p.add_run(text)
    set_font(r2, 9.4, False, INK)
    p.paragraph_format.line_spacing = 1.12


def configure_document(doc: Document) -> None:
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(0.82)
    section.bottom_margin = Inches(0.72)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)

    normal = doc.styles["Normal"]
    normal.font.name = "STSong"
    for key in ("w:ascii", "w:hAnsi", "w:eastAsia", "w:cs"):
        normal._element.rPr.rFonts.set(qn(key), "STSong")
    normal.font.size = Pt(10.5)
    normal.font.color.rgb = RGBColor.from_string(INK)
    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = 1.22

    for name, size, color, before, after in (
        ("Title", 28, INK, 0, 10),
        ("Heading 1", 17, BLUE, 18, 9),
        ("Heading 2", 13, INK, 13, 6),
        ("Heading 3", 11, INK, 10, 5),
    ):
        style = doc.styles[name]
        style.font.name = "STSong"
        for key in ("w:ascii", "w:hAnsi", "w:eastAsia", "w:cs"):
            style._element.rPr.rFonts.set(qn(key), "STSong")
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.color.rgb = RGBColor.from_string(color)
        style.paragraph_format.space_before = Pt(before)
        style.paragraph_format.space_after = Pt(after)
        style.paragraph_format.keep_with_next = True

    header = section.header
    header.is_linked_to_previous = False
    hp = header.paragraphs[0]
    hp.alignment = WD_ALIGN_PARAGRAPH.LEFT
    hp.paragraph_format.space_after = Pt(4)
    r = hp.add_run("FACT ATLAS  /  DEMO PRODUCTION BOOK  ·  演示视频制作手册")
    set_font(r, 7.5, True, MUTED)
    set_paragraph_border(hp, color="B7BAB5", size=6)

    footer = section.footer
    footer.is_linked_to_previous = False
    fp = footer.paragraphs[0]
    fp.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    fp.paragraph_format.space_before = Pt(4)
    r = fp.add_run("AI³ GROWTH HACKATHON 2026   ·   ")
    set_font(r, 7.5, True, MUTED)
    add_field(fp, "PAGE")

    doc.core_properties.title = "Fact Atlas 演示视频字幕与分镜"
    doc.core_properties.subject = "AI³ Growth Hackathon 2026 · Track 3"
    doc.core_properties.author = "Fact Atlas"
    doc.core_properties.keywords = "Fact Atlas, FactRelay, Gonka, Mapbox, demo video, subtitles, AI fact checking"


def build_doc(output: Path) -> None:
    doc = Document()
    configure_document(doc)

    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(10)
    r = p.add_run("AI³ GROWTH HACKATHON 2026  ·  TRACK 3")
    set_font(r, 8.5, True, VIOLET)

    title = doc.add_paragraph(style="Title")
    title.paragraph_format.space_after = Pt(4)
    r = title.add_run("Fact Atlas")
    set_font(r, 31, True, INK)
    subtitle = doc.add_paragraph()
    subtitle.paragraph_format.space_after = Pt(3)
    r = subtitle.add_run("2:30 Demo Video Script")
    set_font(r, 20, True, INK)
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(16)
    r = p.add_run("演示视频字幕与分镜 · 中文旁白 + 英文字幕")
    set_font(r, 13, True, MUTED)

    metrics = doc.add_table(rows=1, cols=4)
    metrics.style = "Table Grid"
    set_table_geometry(metrics, [2340, 2340, 2340, 2340])
    metric_data = [
        ("02:30", "TARGET · 目标时长", VIOLET),
        ("1920 × 1080", "CANVAS · 画面", CYAN),
        ("30 FPS", "CAPTURE · 帧率", LIME),
        ("CN → EN", "VOICE / SUBS · 声音/字幕", YELLOW),
    ]
    for cell, (value, label, fill) in zip(metrics.rows[0].cells, metric_data):
        shade(cell, fill)
        p = cell.paragraphs[0]
        p.paragraph_format.space_after = Pt(1)
        r = p.add_run(value + "\n")
        set_font(r, 15 if value != "1920 × 1080" else 12.5, True, INK)
        r2 = p.add_run(label)
        set_font(r2, 6.5, True, INK)

    doc.add_paragraph()
    callout = doc.add_table(rows=1, cols=1)
    callout.style = "Table Grid"
    set_table_geometry(callout, [9360])
    c = callout.cell(0, 0)
    shade(c, PAPER)
    p = c.paragraphs[0]
    r = p.add_run("RECORDING RULE · 录制原则\n")
    set_font(r, 8, True, VIOLET)
    r2 = p.add_run("Show one real Gonka run. Keep both upstream Request IDs readable. Never expose the API key or personal information.\n必须展示一次真实 Gonka 核查与两条可读回执；不得录入 API Key 或任何个人信息。")
    set_font(r2, 10.5, True, INK)

    doc.add_heading("Recording setup / 录制设置", level=1)
    bullets = [
        "Browser zoom at 100%; one clean tab; close password managers, email, and unrelated tabs. / 浏览器缩放 100%，仅保留干净标签页。",
        "Chinese narration at a calm 1.0× pace; English subtitles no more than two lines. / 中文旁白自然语速；英文字幕最多两行。",
        "Use direct cuts. The card transitions already provide the visual rhythm. / 使用直接切镜，卡片翻页即为主要视觉节奏。",
        "Required on screen: both model names, one public source, Truth Score, and real non-null Request IDs. / 必须展示双模型、公开来源、评分与真实回执。",
    ]
    for item in bullets:
        p = doc.add_paragraph(style="List Bullet")
        p.paragraph_format.space_after = Pt(4)
        set_font(p.add_run(item), 10, False, INK)

    doc.add_page_break()
    doc.add_heading("Scene-by-scene production script / 逐镜头制作脚本", level=1)
    intro = doc.add_paragraph("Read the Chinese narration exactly as written. English lines are the subtitle master and may be pasted into the editor without rewriting. / 中文旁白按原文录制；英文行即字幕母版，可直接进入剪辑软件。")
    intro.paragraph_format.space_after = Pt(10)

    for index, scene in enumerate(SCENES):
        # Scene 03 already flows naturally to a new page after the expanded
        # responsive opening. An explicit break there would create a blank page.
        if index in {4, 6, 8}:
            doc.add_page_break()
        bar = doc.add_table(rows=1, cols=2)
        bar.style = "Table Grid"
        set_table_geometry(bar, [1680, 7680])
        shade(bar.cell(0, 0), scene["color"])
        shade(bar.cell(0, 1), PAPER)
        p = bar.cell(0, 0).paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run(f'{scene["number"]}\n{scene["time"]}')
        set_font(r, 8.5, True, INK)
        p = bar.cell(0, 1).paragraphs[0]
        r = p.add_run(scene["title"])
        set_font(r, 12, True, INK)

        add_label_paragraph(doc, "Screen / 画面", scene["screen"], WHITE)
        add_label_paragraph(doc, "Chinese narration / 中文旁白", scene["narration"], VIOLET_SOFT)

        subs = doc.add_table(rows=len(scene["subtitles"]), cols=2)
        subs.style = "Table Grid"
        set_table_geometry(subs, [2130, 7230])
        for row_idx, (timecode, text) in enumerate(scene["subtitles"]):
            shade(subs.cell(row_idx, 0), INK)
            shade(subs.cell(row_idx, 1), WHITE)
            p1 = subs.cell(row_idx, 0).paragraphs[0]
            r1 = p1.add_run(timecode)
            set_font(r1, 7.3, True, WHITE)
            p2 = subs.cell(row_idx, 1).paragraphs[0]
            r2 = p2.add_run(text)
            set_font(r2, 8.8, False, INK)

        spacer = doc.add_paragraph()
        spacer.paragraph_format.space_after = Pt(2)

    doc.add_page_break()
    doc.add_heading("English subtitle master / 英文字幕总表", level=1)
    p = doc.add_paragraph("Keep every cue on screen for the full interval. Use sentence case and a dark translucent background. / 每条字幕完整覆盖对应区间，使用 sentence case 与深色半透明底。")
    p.paragraph_format.space_after = Pt(8)
    all_subs = [subtitle for scene in SCENES for subtitle in scene["subtitles"]]

    def add_subtitle_table(cues: list[tuple[str, str]]) -> None:
        table = doc.add_table(rows=1 + len(cues), cols=2)
        table.style = "Table Grid"
        set_table_geometry(table, [2130, 7230])
        for i, text in enumerate(("TIMECODE · 时间码", "ENGLISH SUBTITLE · 英文字幕")):
            shade(table.cell(0, i), INK)
            r = table.cell(0, i).paragraphs[0].add_run(text)
            set_font(r, 7.5, True, WHITE)
        for row_idx, (timecode, text) in enumerate(cues, start=1):
            shade(table.cell(row_idx, 0), VIOLET_SOFT if row_idx % 2 else PAPER)
            shade(table.cell(row_idx, 1), WHITE)
            set_font(table.cell(row_idx, 0).paragraphs[0].add_run(timecode), 7.5, True, INK)
            set_font(table.cell(row_idx, 1).paragraphs[0].add_run(text), 8.6, False, INK)

    add_subtitle_table(all_subs[:10])
    doc.add_page_break()
    doc.add_heading("English subtitle master — continued / 英文字幕续表", level=1)
    p = doc.add_paragraph("Cues 11–19 complete the same uninterrupted 2:30 timeline. / 第 11–19 条延续同一条完整的 2 分 30 秒时间线。")
    p.paragraph_format.space_after = Pt(8)
    add_subtitle_table(all_subs[10:])

    doc.add_page_break()
    doc.add_heading("Pronunciation and on-screen terms / 发音与术语", level=1)
    terms = [
        ("Fact Atlas", "“Fact Atlas”; two English words spoken naturally / 两个英文词自然连读"),
        ("Gonka", "Keep the product name visible while it is spoken / 发音时画面保留 Gonka 名称"),
        ("Kimi-K2.6", "“Kimi K two point six”"),
        ("MiniMax-M2.7", "“MiniMax M two point seven”"),
        ("Truth Score", "Chinese narration may say 真实度评分; keep the English UI term visible"),
        ("Request ID", "Chinese narration may say 请求回执; keep the real ID readable"),
        ("Mapbox", "Keep the official name in English; it is the Atlas basemap, not an inference provider"),
    ]
    term_table = doc.add_table(rows=len(terms), cols=2)
    term_table.style = "Table Grid"
    set_table_geometry(term_table, [2200, 7160])
    for idx, (term, note) in enumerate(terms):
        term_colors = [LIME, CYAN, YELLOW, VIOLET_SOFT, PINK, PAPER]
        shade(term_table.cell(idx, 0), term_colors[idx % len(term_colors)])
        set_font(term_table.cell(idx, 0).paragraphs[0].add_run(term), 9.5, True, INK)
        set_font(term_table.cell(idx, 1).paragraphs[0].add_run(note), 9.2, False, INK)

    doc.add_heading("Final recording and privacy check / 最终录制与隐私检查", level=1)
    checklist = [
        "Use a real live result; do not record only the preview fixture. / 使用真实运行结果，不只录预览数据。",
        "Both Gonka Request IDs are non-null and readable. / 两条 Gonka 回执非空且可读。",
        "No API key, .env.local, email, phone, password manager, or unrelated tab is visible. / 不出现密钥与个人信息。",
        "Pause 1–2 seconds after each card transition. / 每次翻卡后停留 1–2 秒。",
        "Watch the exported MP4 once with sound and once muted. / 导出后分别有声、静音完整检查。",
        "Test the public/unlisted link from a signed-out window. / 在未登录窗口测试公开视频链接。",
    ]
    for item in checklist:
        p = doc.add_paragraph(style="List Bullet")
        set_font(p.add_run(item), 10, False, INK)

    note = doc.add_table(rows=1, cols=1)
    note.style = "Table Grid"
    set_table_geometry(note, [9360])
    shade(note.cell(0, 0), YELLOW)
    p = note.cell(0, 0).paragraphs[0]
    r = p.add_run("FINAL EDITOR NOTE · 最终剪辑提示\n")
    set_font(r, 8, True, INK)
    r2 = p.add_run("Use cuts rather than decorative transitions. Add one quiet click at the first card flip only. Keep music at least 18 dB below narration—or omit it. Never speed up the score or Request ID shots beyond readability.\n以直接切镜为主，仅在第一次翻卡时加入轻微点击音；背景音乐至少比旁白低 18 dB，或不使用。评分与回执镜头必须保持可读。")
    set_font(r2, 9.7, False, INK)

    output.parent.mkdir(parents=True, exist_ok=True)
    doc.save(output)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    build_doc(args.output)
